my_dbt_profile:
  outputs:
    dev:
      type: "{{ env_var('DBT_TYPE') }}"
      host: "{{ env_var('DBT_HOST') }}"
      port: 5432
      user: "{{ env_var('APP_POSTGRES_USER') }}"
      password: "{{ env_var('APP_POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('APP_POSTGRES_DB') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
  target: "{{ env_var('DBT_TARGET') }}"
