my_dbt_profile:
  outputs:
    dev:
      type: postgres
      host: postgres
      port: 5432
      user: "{{ env_var('APP_POSTGRES_USER') }}"
      password: "{{ env_var('APP_POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('APP_POSTGRES_DB') }}"
      schema: public
  target: dev
