my_dbt_profile:
  outputs:
    dev:
      type: postgres
      host: postgres
      port: 5432
      user: ${APP_POSTGRES_USER}
      password: ${APP_POSTGRES_PASSWORD}
      dbname: ${APP_POSTGRES_DB}
      schema: public
  target: dev
