# Static configuration
# Entrypoints
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: ":443"

# Providers
providers:
  docker:
    exposedByDefault: false # Don't expose all containers by default